name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Debug printouts
        run: |
          echo "Current Directory:"
          echo "import os; print(os.getcwd())" | python
          echo "Current Directory Contents:"
          echo "import os; print(os.listdir())" | python
          echo "Try to import package:"
          echo "from conversational_gcode.options.JobOptions import JobOptions" | python
      - name: Python 3
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .
          echo
          echo "Current Directory:"
          echo "import os; print(os.getcwd())" | python3
          echo "Current Directory Contents:"
          echo "import os; print(os.listdir())" | python3
          echo "Try to import package:"
          echo "from conversational_gcode.options.JobOptions import JobOptions" | python3
      - name: Test
        uses: onichandame/python-test-action@v1
        with:
          args: discover -s tests
